apiVersion: v1
kind: Service
metadata:
  name:  svc-nodeapp-demo
spec:
  selector:
    app:  nodeappdemo
  type:  LoadBalancer
  ports:
    - port:  3000      
      targetPort:  3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeappdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeappdemo
  template:
    metadata:
      labels:
        app: nodeappdemo
    spec:
      containers:
      - name: nodeappdemo
        image: __image__
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"        
        ports:
        - containerPort: 3000   
        env:
          - name: BUILD_IMAGE
            value: __version__
          - name: ENVIRONMENT
            value: __environment__            