name: Deploy on Kubernetes

on:
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.REGISTRY_SERVER }}/nodeappdemo:${{ github.sha }}

jobs:
  build-node-app-image:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2   
          
    #   - name: Log in to container registry
    #     uses: docker/login-action@v1
    #     with:
    #       registry: ${{ secrets.REGISTRY_SERVER }}
    #       username: ${{ secrets.REGISTRY_USERNAME }}
    #       password: ${{ secrets.REGISTRY_PASSWORD }}           

      - name: Build docker image
        run: |          
          docker build -t ${{ env.IMAGE_NAME }} .
          docker push ${{ env.IMAGE_NAME }}
        working-directory: ./src  
    
      - name: Deploy to container registry
        run: |
          docker push ${{ env.IMAGE_NAME }}